### ISSUE TITLE
Some context parameters are ignored from web.xml

### ISSUE THREAD

**Issue by Pilpin** [melloware/quarkus-faces#208]
Hello,

It seems that some context parameters inside the web.xml file are ignored, more specifically the `org.apache.myfaces.NUMBER_OF_VIEWS_IN_SESSION` and `org.apache.myfaces.NUMBER_OF_SEQUENTIAL_VIEWS_IN_SESSION`.
I tried changing their values and displaying it in the topbar with `#{initParam['_paramName_']}` but the values stayed unchanged, respectively 15 and 3.
Some values do work though, `org.apache.myfaces.USE_LAMBDA_METAFACTORY` for example.

Even changing `javax.faces.PROJECT_STAGE` from **web.xml** did not work, but this one worked when put in the **application.properties** file.

Would you have an idea of why this is happening ? 

FYI I've [written a question on stackoverflow](https://stackoverflow.com/questions/74560196/context-params-ignored-from-web-xml-by-myfaces-with-quarkus) about this and I would have opened a ticket on MyFaces' jira, but I can't create an account to do so.

**Comment by melloware** [comment]
Quarkus is not a standard EE container so not all things will be the same.   The `javax.faces.PROJECT_STAGE` in `application.properties` is the right place to put it since its quarkus.

However good question on the web.xml init parameters I would expect them to be read.  But really like you said that is a MyFaces question.

**Comment by melloware** [comment]
MyFaces issue created: https://issues.apache.org/jira/browse/MYFACES-4509
